In [1]:
import cfg

In [2]:
import numpy as np

In [3]:
import torch

In [4]:
import torch.nn as nn

In [5]:
from datasets.camera_light_dataset import CameraLightDataset

In [6]:
d = CameraLightDataset(input_dir = '.', cfg_file = 'config.cfg',task_name = 'normals', target_dir = 'targets/normals')

In [7]:
d.flat_cfg[0]

{'at': [3.72811, 87.9981, -82.1874],
 'color': [10000000, 10000000, 10000000],
 'eye': [61.41559999999998, 102.11, -1325.25],
 'fov': 10.1592,
 'light': [61.4156, 102.11, -1325.25],
 'size': [128, 128],
 'spp': 128,
 'up': [-0.0005256740209828103, 0.9999357047659718, 0.011327400452123822],
 'normals': 'normal_0000.png',
 'rendering': 'out-0000-0000.png',
 'i': '0',
 'j': '0'}

In [8]:
from graphics_math import lookat

In [9]:
entry = d.flat_cfg[0]

In [10]:
eye = entry['eye']

In [11]:
at = entry['at']

In [12]:
up = entry['up']

In [13]:
eye = np.array([eye]).transpose()

In [14]:
at = np.array([at]).transpose()

In [15]:
up = np.array([up]).transpose()

In [16]:
lookat(eye, at, up)

array([[-9.98924906e-01,  2.88074634e-09, -4.63576577e-02,
        -8.59136769e-02],
       [-5.25674021e-04,  9.99935705e-01,  1.13274005e-02,
        -8.70595128e+01],
       [ 4.63546771e-02,  1.13395914e-02, -9.98860680e-01,
        -1.32774490e+03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [17]:
matrices = [lookat(np.array([entry['eye']]).transpose(), np.array([entry['at']]).transpose(), np.array([entry['up']]).transpose()) for entry in d.flat_cfg]

In [18]:
max_vals = matrices[0]

In [19]:
for m in matrices:
    max_vals = np.maximum(max_vals, m)

In [20]:
max_vals

array([[ 9.99864390e-01,  1.13395914e-02,  9.99800478e-01,
         8.32644401e+01],
       [ 9.99864390e-01,  9.99935705e-01,  9.99800478e-01,
         1.20462085e+02],
       [ 9.99864390e-01,  9.99935705e-01,  9.99800478e-01,
        -1.12401838e+03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [21]:
min_vals = matrices[0]

In [22]:
for m in matrices:
    min_vals = np.minimum(min_vals, m)

In [23]:
min_vals

array([[-9.99864390e-01, -1.13395914e-02, -9.99800478e-01,
        -8.32644401e+01],
       [-9.99864390e-01, -9.99935705e-01, -9.99800478e-01,
        -1.20462085e+02],
       [-9.99864390e-01, -9.99935705e-01, -9.99800478e-01,
        -1.36494255e+03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [24]:
divisor = np.maximum(max_vals - min_vals, np.ones(max_vals.shape))

In [25]:
divisor

array([[  1.99972878,   1.        ,   1.99960096, 166.52888014],
       [  1.99972878,   1.99987141,   1.99960096, 240.92417002],
       [  1.99972878,   1.99987141,   1.99960096, 240.92417002],
       [  1.        ,   1.        ,   1.        ,   1.        ]])

In [26]:
(matrices - min_vals) / divisor - 0.5

array([[[-4.99530194e-01, -4.88660406e-01, -2.31834545e-02,
         -5.15908573e-04],
        [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
         -3.61356491e-01],
        [ 2.31804821e-02,  5.67016029e-03, -4.99530007e-01,
         -3.45604345e-01],
        [-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
         -5.00000000e-01]],

       [[-5.00000000e-01, -4.89372425e-01,  8.22804147e-03,
          3.08803692e-02],
        [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
         -3.61356491e-01],
        [-8.23101973e-03,  5.65897161e-03, -5.00000000e-01,
         -3.44944765e-01],
        [-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
         -5.00000000e-01]],

       [[-4.98496534e-01, -4.90081633e-01,  3.96070651e-02,
          6.21547763e-02],
        [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
         -3.61356491e-01],
        [-3.96100375e-02,  5.62544956e-03, -4.98496721e-01,
         -3.42923846e-01],
        [-5.00000000e-01, -5.00000000e-

In [27]:
matrices[0]

array([[-9.98924906e-01,  2.88074634e-09, -4.63576577e-02,
        -8.59136769e-02],
       [-5.25674021e-04,  9.99935705e-01,  1.13274005e-02,
        -8.70595128e+01],
       [ 4.63546771e-02,  1.13395914e-02, -9.98860680e-01,
        -1.32774490e+03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [28]:
(matrices[0]-min_vals) / divisor - .5

array([[-4.99530194e-01, -4.88660406e-01, -2.31834545e-02,
        -5.15908573e-04],
       [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
        -3.61356491e-01],
       [ 2.31804821e-02,  5.67016029e-03, -4.99530007e-01,
        -3.45604345e-01],
       [-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
        -5.00000000e-01]])

In [29]:
normalized = [(v - min_vals) / divisor - .5 for v in matrices]

In [30]:
normalized

[array([[-4.99530194e-01, -4.88660406e-01, -2.31834545e-02,
         -5.15908573e-04],
        [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
         -3.61356491e-01],
        [ 2.31804821e-02,  5.67016029e-03, -4.99530007e-01,
         -3.45604345e-01],
        [-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
         -5.00000000e-01]]),
 array([[-5.00000000e-01, -4.89372425e-01,  8.22804147e-03,
          3.08803692e-02],
        [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
         -3.61356491e-01],
        [-8.23101973e-03,  5.65897161e-03, -5.00000000e-01,
         -3.44944765e-01],
        [-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
         -5.00000000e-01]]),
 array([[-4.98496534e-01, -4.90081633e-01,  3.96070651e-02,
          6.21547763e-02],
        [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
         -3.61356491e-01],
        [-3.96100375e-02,  5.62544956e-03, -4.98496721e-01,
         -3.42923846e-01],
        [-5.00000000e-01, -5.00000000e-

In [31]:
(matrices[4] - min_vals) / divisor

array([[0.01039871, 0.00851955, 0.60177296, 0.62384524],
       [0.49973713, 1.        , 0.50566483, 0.13864351],
       [0.39822412, 0.50549202, 0.01039816, 0.16516477],
       [0.        , 0.        , 0.        , 0.        ]])

In [32]:
(matrices[1] - min_vals) / divisor - 0.5

array([[-5.00000000e-01, -4.89372425e-01,  8.22804147e-03,
         3.08803692e-02],
       [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
        -3.61356491e-01],
       [-8.23101973e-03,  5.65897161e-03, -5.00000000e-01,
        -3.44944765e-01],
       [-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
        -5.00000000e-01]])

In [33]:
normalized=(matrices - min_vals) / divisor - 0.5

In [34]:
normalized

array([[[-4.99530194e-01, -4.88660406e-01, -2.31834545e-02,
         -5.15908573e-04],
        [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
         -3.61356491e-01],
        [ 2.31804821e-02,  5.67016029e-03, -4.99530007e-01,
         -3.45604345e-01],
        [-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
         -5.00000000e-01]],

       [[-5.00000000e-01, -4.89372425e-01,  8.22804147e-03,
          3.08803692e-02],
        [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
         -3.61356491e-01],
        [-8.23101973e-03,  5.65897161e-03, -5.00000000e-01,
         -3.44944765e-01],
        [-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
         -5.00000000e-01]],

       [[-4.98496534e-01, -4.90081633e-01,  3.96070651e-02,
          6.21547763e-02],
        [-2.62872659e-04,  5.00000000e-01,  5.66483049e-03,
         -3.61356491e-01],
        [-3.96100375e-02,  5.62544956e-03, -4.98496721e-01,
         -3.42923846e-01],
        [-5.00000000e-01, -5.00000000e-

In [35]:
new_min = normalized[0]

In [36]:
for m in normalized:
    new_min  = np.minimum(new_min, m)

In [37]:
new_min

array([[-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5]])

In [38]:
new_max  = normalized[0]

In [39]:
for m in normalized:
    new_max  = np.maximum(new_max, m)

In [40]:
new_max

array([[ 0.5       , -0.47732082,  0.5       ,  0.5       ],
       [ 0.5       ,  0.5       ,  0.5       ,  0.5       ],
       [ 0.5       ,  0.5       ,  0.5       ,  0.5       ],
       [-0.5       , -0.5       , -0.5       , -0.5       ]])

In [41]:
d = CameraLightDataset(input_dir = '.', cfg_file = 'config.cfg',task_name = 'normals', target_dir = 'targets/normals')

In [42]:
d.normalized_matrices

array([[[-0.49906052, -0.48866041,  0.45344282,  0.5       ],
        [ 0.49933872,  0.5       ,  0.5       ,  0.5       ],
        [ 0.5       ,  0.5       , -0.4990602 ,  0.5       ],
        [-0.5       , -0.5       , -0.5       , -0.5       ]],

       [[-0.5       , -0.48937242,  0.51625328,  0.56285741],
        [ 0.49933872,  0.5       ,  0.5       ,  0.5       ],
        [ 0.43996049,  0.49997787, -0.5       ,  0.50427201],
        [-0.5       , -0.5       , -0.5       , -0.5       ]],

       [[-0.49699348, -0.49008163,  0.5789988 ,  0.62547083],
        [ 0.49933872,  0.5       ,  0.5       ,  0.5       ],
        [ 0.37998306,  0.49991158, -0.49699404,  0.51736124],
        [-0.5       , -0.5       , -0.5       , -0.5       ]],

       ...,

       [[-0.47268081, -0.48653558,  0.26709611,  0.31244344],
        [ 0.48472755,  0.49866364,  0.5603685 ,  0.65886179],
        [ 0.67765551,  0.56186609, -0.47005085,  0.39746098],
        [-0.5       , -0.5       , -0.5       , -0.