In [1]:
import torch

In [2]:
import torch.nn as nn

In [6]:
light_size=3

In [7]:
from numpy import linalg as la

In [23]:
light_position = torch.rand((1,3))

In [24]:
type(light_position)

torch.Tensor

In [25]:
print(light_position)

tensor([[0.9017, 0.8474, 0.8100]])


In [26]:
img=light_position.repeat(6, 6, 1)

In [27]:
img.shape

torch.Size([6, 6, 3])

In [29]:
img[0][0]

tensor([0.9017, 0.8474, 0.8100])

In [57]:
img.permute((2, 0, 1)).unsqueeze(0).shape

torch.Size([1, 3, 6, 6])

In [45]:
x=torch.rand((1, 3, 6, 6))

In [52]:
x

tensor([[[[0.8287, 0.0731, 0.5440, 0.0855, 0.5084, 0.3009],
          [0.0813, 0.7854, 0.5659, 0.3435, 0.7670, 0.7568],
          [0.4748, 0.9192, 0.6038, 0.2108, 0.6549, 0.4182],
          [0.8787, 0.0753, 0.5271, 0.3589, 0.1788, 0.3477],
          [0.7707, 0.4783, 0.6243, 0.4552, 0.2140, 0.6123],
          [0.9489, 0.6648, 0.3219, 0.7975, 0.6295, 0.8089]],

         [[0.1296, 0.6604, 0.5591, 0.4989, 0.2586, 0.7903],
          [0.8603, 0.5162, 0.2454, 0.2129, 0.5301, 0.7549],
          [0.2259, 0.7712, 0.5913, 0.6639, 0.3823, 0.5475],
          [0.7397, 0.2914, 0.0727, 0.3658, 0.3928, 0.8585],
          [0.9668, 0.4078, 0.4069, 0.2776, 0.3524, 0.6987],
          [0.6746, 0.9352, 0.8597, 0.8617, 0.0859, 0.1276]],

         [[0.6243, 0.4695, 0.7740, 0.2752, 0.9670, 0.9205],
          [0.5099, 0.2579, 0.0619, 0.0762, 0.9242, 0.0701],
          [0.8505, 0.9819, 0.7685, 0.0410, 0.8593, 0.6055],
          [0.1043, 0.4558, 0.8570, 0.1089, 0.7892, 0.0735],
          [0.8549, 0.1042, 0.1866, 0

In [56]:
torch.repeat

AttributeError: module 'torch' has no attribute 'repeat'