In [2]:
import torch

In [3]:
import torch.nn as nn

In [4]:
camera_matrix_size=16

In [5]:
light_size=3

In [6]:
from numpy import linalg as la

In [7]:
camera_matrix = torch.rand((4,4))

In [8]:
camera_matrix / la.norm(camera_matrix.numpy(), 'fro')

tensor([[0.2428, 0.0698, 0.0615, 0.2900],
        [0.0340, 0.1867, 0.0678, 0.5392],
        [0.3164, 0.0886, 0.2977, 0.2419],
        [0.3897, 0.0466, 0.3239, 0.0538]])

In [9]:
light_position = torch.rand((1,3))

In [10]:
light_position / la.norm(light_position.numpy(),'fro')

tensor([[0.3663, 0.4576, 0.8102]])

In [11]:
camera_matrix.view(-1, 1, 1, 16).shape

torch.Size([1, 1, 1, 16])

In [12]:
light_position.view(-1, 1, 1, 3).shape

torch.Size([1, 1, 1, 3])

In [13]:
torch.cat((camera_matrix.view(-1, 1, 1, 16), light_position.view(-1, 1, 1, 3)), 3).shape

torch.Size([1, 1, 1, 19])

In [14]:
input_values = torch.cat((camera_matrix.view(-1, 1, 1, 16), light_position.view(-1, 1, 1, 3)), 3)

In [15]:
input_values.view(-1, 19).shape

torch.Size([1, 19])

In [16]:
fc0 = nn.Linear(19, 1024)

In [17]:
x = input_values.view(-1, 19)

In [18]:
x = fc0(x)

In [19]:
fc1 = nn.Linear(1024, 4096)

In [20]:
x = fc1(x)

In [21]:
fc2 = nn.Linear(4096, 4096)

In [22]:
x = fc2(x)

In [23]:
x.shape

torch.Size([1, 4096])

In [24]:
x = x.view(-1, 256, 4, 4)

In [25]:
deconv3 = nn.ConvTranspose2d(256, 512, kernel_size = (3, 3), padding = 1)

In [26]:
x = deconv3(x)

In [27]:
x.shape

torch.Size([1, 512, 4, 4])

In [28]:
conv4 = nn.Conv2d(512, 512, kernel_size = (3, 3), padding = 1)

In [29]:
x = conv4(x)

In [30]:
x.shape

torch.Size([1, 512, 4, 4])

In [31]:
deconv5 = nn.ConvTranspose2d(512, 512, kernel_size = (3, 3), padding = 1)

In [32]:
x = deconv5(x)

In [33]:
x.shape

torch.Size([1, 512, 4, 4])

In [34]:
conv6 = nn.Conv2d(512, 512, kernel_size = (3, 3), padding = 1)

In [35]:
x = conv6(x)

In [36]:
x.shape

torch.Size([1, 512, 4, 4])

In [37]:
deconv7 = nn.ConvTranspose2d(512, 256, kernel_size = (5, 5))

In [38]:
x = deconv7(x)

In [39]:
x.shape

torch.Size([1, 256, 8, 8])

In [40]:
conv8 = nn.Conv2d(256, 256, kernel_size = (3, 3), padding = 1)

In [41]:
x = conv8(x)

In [42]:
x.shape

torch.Size([1, 256, 8, 8])

In [43]:
deconv9 = nn.ConvTranspose2d(256, 128, kernel_size = (5, 5), stride = 2, padding = 2, output_padding = 1)

In [44]:
x = deconv9(x)

In [45]:
x.shape

torch.Size([1, 128, 16, 16])

In [46]:
conv10 = nn.Conv2d(128, 128, kernel_size = (3, 3), padding = 1)

In [47]:
x = conv10(x)

In [48]:
x.shape

torch.Size([1, 128, 16, 16])

In [49]:
deconv11 = nn.ConvTranspose2d(128, 64, kernel_size = (5, 5), stride = 2, padding = 2, output_padding = 1)

In [50]:
x = deconv11(x)

In [51]:
x.shape

torch.Size([1, 64, 32, 32])

In [52]:
conv12 = nn.Conv2d(64, 64, kernel_size = (3, 3), padding = 1)

In [53]:
x = conv12(x)

In [54]:
x.shape

torch.Size([1, 64, 32, 32])

In [55]:
deconv13 = nn.ConvTranspose2d(64, 32, kernel_size = (5, 5), stride = 2, padding = 2, output_padding = 1)

In [56]:
x = deconv13(x)

In [57]:
x.shape

torch.Size([1, 32, 64, 64])

In [58]:
conv14 = nn.Conv2d(32, 32, kernel_size = (3, 3), padding = 1)

In [59]:
x = conv14(x)

In [60]:
x.shape

torch.Size([1, 32, 64, 64])

In [61]:
deconv15 = nn.ConvTranspose2d(32, 16, kernel_size = (5, 5), stride = 2, padding = 2, output_padding = 1)

In [62]:
x = deconv15(x)

In [63]:
x.shape

torch.Size([1, 16, 128, 128])

In [64]:
conv16 = nn.Conv2d(16, 3, kernel_size = 3, padding = 1)

In [65]:
x = conv16(x)

In [66]:
x.shape

torch.Size([1, 3, 128, 128])

In [67]:
sig16 = nn.Sigmoid()

In [68]:
x = sig16(x)

In [69]:
x.shape

torch.Size([1, 3, 128, 128])

In [70]:
x

tensor([[[[0.5144, 0.5140, 0.5158,  ..., 0.5146, 0.5147, 0.5143],
          [0.5108, 0.5097, 0.5102,  ..., 0.5099, 0.5114, 0.5093],
          [0.5141, 0.5120, 0.5137,  ..., 0.5120, 0.5116, 0.5105],
          ...,
          [0.5096, 0.5078, 0.5089,  ..., 0.5087, 0.5106, 0.5088],
          [0.5134, 0.5111, 0.5130,  ..., 0.5111, 0.5121, 0.5100],
          [0.5089, 0.5076, 0.5075,  ..., 0.5069, 0.5079, 0.5091]],

         [[0.4940, 0.4952, 0.4935,  ..., 0.4949, 0.4921, 0.4939],
          [0.4896, 0.4919, 0.4882,  ..., 0.4910, 0.4896, 0.4902],
          [0.4934, 0.4936, 0.4914,  ..., 0.4925, 0.4897, 0.4915],
          ...,
          [0.4897, 0.4909, 0.4887,  ..., 0.4906, 0.4893, 0.4905],
          [0.4918, 0.4928, 0.4914,  ..., 0.4914, 0.4907, 0.4909],
          [0.4882, 0.4875, 0.4863,  ..., 0.4872, 0.4859, 0.4860]],

         [[0.4832, 0.4830, 0.4836,  ..., 0.4849, 0.4843, 0.4854],
          [0.4807, 0.4795, 0.4816,  ..., 0.4787, 0.4816, 0.4809],
          [0.4783, 0.4793, 0.4800,  ..., 0

In [71]:
input_values.shape[3]

19

In [72]:
input_dims = input_values.shape[3]

In [73]:
import models as r

In [74]:
p = r.Precoder(input_dims)

In [75]:
output = p(input_values.view(-1,1,1,19))

x.shape = torch.Size([1, 1, 1, 19])


In [76]:
p.estimate_size()

32.821078300476074

In [ ]:
from torchvision import models
from summary import summary

In [ ]:
summary(p.to("cpu"), (1, 1, 1, 10))